<?php
declare(strict_types=1);
ini_set('display_errors','0'); session_set_cookie_params(['httponly'=>true,'samesite'=>'Lax']); session_start();
function env(string $key,string $default=''):string{static $v=null;if($v===null){$v=is_file(__DIR__.'/../.env')?parse_ini_file(__DIR__.'/../.env',false,INI_SCANNER_RAW):[];}return (string)($v[$key]??getenv($key)?:$default);}
function db():PDO{static $pdo;if(!$pdo){$pdo=new PDO('mysql:host='.env('DB_HOST','127.0.0.1').';dbname='.env('DB_NAME','ekstra_demo').';charset=utf8mb4',env('DB_USER','root'),env('DB_PASS'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}return $pdo;}
function e(?string $s):string{return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');} function q(string $sql,array $p=[]):PDOStatement{$s=db()->prepare($sql);$s->execute($p);return $s;}
function me():?array{if(empty($_SESSION['uid']))return null;return q('SELECT u.*,r.slug role,r.name role_name FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?',[$_SESSION['uid']])->fetch()?:null;}
function csrf():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));return $_SESSION['csrf'];} function verify_csrf():void{if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')) throw new RuntimeException('Permintaan tidak valid. Silakan coba lagi.');}
function flash(string $m='',string $type='success'):?array{if($m){$_SESSION['flash']=[$m,$type];return null;}$x=$_SESSION['flash']??null;unset($_SESSION['flash']);return $x;}
function go(string $p):never{header('Location: '.$p);exit;} function require_login():array{$u=me();if(!$u){flash('Silakan masuk terlebih dahulu.','error');go('/login');}return $u;} function allow(array $roles):array{$u=require_login();if(!in_array($u['role'],$roles,true)){http_response_code(403);exit('Akses ditolak.');}return $u;}
function managed_extras(array $u):array{if(in_array($u['role'],['wakasek','kepsek','admin'],true))return q('SELECT * FROM extracurriculars ORDER BY name')->fetchAll();return q('SELECT e.* FROM extracurriculars e LEFT JOIN memberships m ON m.extracurricular_id=e.id AND m.user_id=? LEFT JOIN staff_assignments s ON s.extracurricular_id=e.id AND s.user_id=? WHERE m.id IS NOT NULL OR s.id IS NOT NULL ORDER BY e.name',[$u['id'],$u['id']])->fetchAll();}
function owns_extra(array $u,int $id):bool{foreach(managed_extras($u) as $e)if((int)$e['id']===$id)return true;return false;}
function layout(string $title,string $body,bool $internal=false):void{$u=me();$f=flash();?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> · Ekstra Pacet</title><link rel="stylesheet" href="/assets/style.css"></head><body class="<?=$internal?'internal':''?>"><header><a class="brand" href="/">✦ <span>EKSTRA</span> PACET</a><nav><a href="/ekstrakurikuler">Ekskul</a><a href="/berita">Info</a><?php if($u):?><a href="/dashboard">Dashboard</a><form method="post" action="/logout" class="inline"><input type="hidden" name="csrf" value="<?=csrf()?>"><button>Keluar</button></form><?php else:?><a class="button" href="/login">Masuk Portal</a><?php endif?></nav></header><?php if($f):?><div class="flash <?=$f[1]?>"><?=e($f[0])?></div><?php endif?><main><?=$body?></main><footer>Demo sistem manajemen ekstrakurikuler · <b>NEEDS CONFIRMATION:</b> aturan resmi sekolah dapat dikonfigurasi sebelum produksi.</footer><script src="/assets/app.js"></script></body></html><?php }
