INSERT INTO roles(slug,name) VALUES ('siswa','Siswa'),('inti','Inti Ekstrakurikuler'),('pembina','Pembina'),('pelatih','Pelatih'),('wakasek','Wakasek'),('kepsek','Kepala Sekolah'),('admin','Admin / Developer');
INSERT INTO extracurricular_groups(name) VALUES ('Akademik & Bahasa'),('Kepemimpinan & Sosial'),('Olahraga'),('Seni & Media'),('Kewirausahaan');
INSERT INTO positions(name) VALUES ('Ketua'),('Sekretaris'),('Bendahara'),('Anggota');
INSERT INTO users(role_id,username,password_hash,name,email) VALUES
(1,'demo.siswa','$2y$12$lGwquKDVro96wfczE.7O6.fydqNDppf312wUzgCemvERJ2odB7r1C','Alya Putri','alya@example.test'),(2,'demo.inti','$2y$12$rih3x16LunC1qF1cKwcb6ews2TLyZxrmdKRAjQsec2HTTgq3Deec6','Raka Pratama','raka@example.test'),(3,'demo.pembina','$2y$12$6iu/gdTERqu20QgLo2j5UuvRYEs.LU4yykbeL44rhbzq2vJTB.RiW','Ibu Sari Pembina','sari@example.test'),(4,'demo.pelatih','$2y$12$yUNqssJWLS2izX/MKJ5LSeLriOP8rsID9E6eBrC/BrGj0uPHYIfZi','Pak Dimas Pelatih','dimas@example.test'),(5,'demo.wakasek','$2y$12$KuARtvVSe4OWvNYuhHJH7ux5kxCcDoR24Zgm64xrPg5ZO2nU0ICUW','Ibu Ratna Wakasek','ratna@example.test'),(6,'demo.kepsek','$2y$12$cyRbvZ6bwJgvEfYzvkXuMuOqK0shiPv8wHAVD5573UiltXKRDm/h2','Bapak Arif Kepala Sekolah','arif@example.test'),(7,'demo.admin','$2y$12$LYm5y.jUMlViWZJq/4idv.XE0nuD1P3LiHJyev6FM2pHWvx.EvZSO','Admin Demo','admin@example.test');
INSERT INTO extracurriculars(group_id,name,slug,description,color) VALUES
(1,'ECC','ecc','English Conversation Club untuk komunikasi percaya diri.','#2563eb'),(1,'Nihongo','nihongo','Ruang belajar bahasa dan budaya Jepang.','#db2777'),(2,'Ambalan','ambalan','Pramuka penegak untuk kepemimpinan, layanan, dan petualangan.','#059669'),(2,'Paskib','paskib','Pasukan pengibar bendera yang disiplin dan tangguh.','#dc2626'),(2,'PMR','pmr','Relawan remaja untuk kepedulian dan kesehatan sekolah.','#ef4444'),(2,'Remas','remas','Remaja masjid dengan kegiatan keagamaan dan sosial.','#7c3aed'),(4,'Banjari','banjari','Seni musik hadrah dan kolaborasi.','#b45309'),(2,'PIK-R','pik-r','Pusat informasi dan konseling remaja.','#0891b2'),(3,'Basket','basket','Latihan bola basket dan kompetisi antarsekolah.','#ea580c'),(4,'Dance','dance','Eksplorasi tari modern secara kreatif.','#ec4899'),(3,'E-Sport','e-sport','Kompetisi gim dengan sportivitas digital.','#4f46e5'),(3,'Futsal','futsal','Tim futsal sekolah yang aktif berlatih.','#16a34a'),(3,'Gateball','gateball','Olahraga presisi dan strategi.','#0f766e'),(3,'Karate','karate','Pembinaan bela diri dan karakter.','#be123c'),(3,'Pencak Silat','pencak-silat','Warisan bela diri nusantara.','#9f1239'),(3,'Spartan','spartan','Kebugaran dan tantangan ketahanan.','#334155'),(3,'Volly','volly','Latihan bola voli dan kerja sama tim.','#f97316'),(4,'Teater','teater','Panggung ekspresi, naskah, dan pertunjukan.','#9333ea'),(4,'Karawitan','karawitan','Pelestarian musik tradisional Jawa.','#a16207'),(4,'Multimedia','multimedia','Kreasi visual, dokumentasi, dan media digital.','#0284c7'),(4,'Music','music','Kolaborasi musik modern siswa.','#7c3aed'),(4,'Paduan Suara','paduan-suara','Harmoni vokal untuk acara sekolah.','#e11d48'),(4,'Tari','tari','Tari tradisi dan pertunjukan kreatif.','#db2777'),(1,'LKTI','lkti','Karya tulis ilmiah dan riset siswa.','#2563eb'),(5,'Spekta','spekta','Event kreatif dan apresiasi bakat.','#d97706'),(5,'Kopsis','kopsis','Koperasi siswa dan literasi bisnis.','#16a34a'),(5,'Kewirausahaan','kewirausahaan','Usaha siswa yang beretika dan inovatif.','#0891b2');
INSERT INTO memberships(user_id,extracurricular_id,position_id) VALUES (1,3,4),(1,1,4),(1,20,4),(2,3,1);
INSERT INTO staff_assignments(user_id,extracurricular_id) VALUES (3,3),(4,9);
INSERT INTO activities(extracurricular_id,title,activity_date,activity_time,location,material,instructor,description,created_by) VALUES (3,'Latihan Kepemimpinan Ambalan','2026-09-20','15:30','Lapangan sekolah','Manajemen regu','Ibu Sari Pembina','Latihan rutin dan pembagian tugas kemah.',2),(1,'English Speaking Circle','2026-09-22','15:00','Ruang Bahasa','Public speaking','Kak Alya','Latihan percakapan tema sekolah.',2),(9,'Drill Dasar Basket','2026-09-21','16:00','Gor sekolah','Passing dan defense','Pak Dimas','Latihan teknik dasar tim basket.',4);
INSERT INTO journals(extracurricular_id,journal_date,title,content,created_by) VALUES (3,'2026-09-10','Jurnal latihan perdana','Kehadiran baik. Materi kepemimpinan regu telah disampaikan.',2);
INSERT INTO proposals(extracurricular_id,title,status,created_by) VALUES (3,'Proposal Kemah Bakti Ambalan','submitted',2),(9,'Proposal Turnamen Basket Pelajar','forwarded',4);
INSERT INTO proposal_versions(proposal_id,version_no,notes,created_by) VALUES (1,1,'Dokumen contoh untuk alur demo.',2),(2,1,'Dokumen contoh yang telah diteruskan Wakasek.',4);
INSERT INTO proposal_reviews(proposal_id,reviewer_id,action,notes) VALUES (2,5,'forward','Layak diteruskan untuk keputusan akhir.');
INSERT INTO financial_transactions(extracurricular_id,transaction_date,type,description,amount,created_by) VALUES (3,'2026-09-01','income','Iuran kegiatan September',450000,2),(3,'2026-09-08','expense','Perlengkapan kegiatan',125000,2),(9,'2026-09-05','income','Sponsor latihan',600000,4);
INSERT INTO news(title,excerpt,published_at) VALUES ('Pekan Ekskul Dibuka','Mari kenali ruang tumbuh, karya, dan kolaborasi siswa melalui ekstrakurikuler.','2026-09-14'),('Jadwal Latihan Semester Ganjil','Setiap pembina dapat memperbarui jadwal kegiatan melalui portal internal.','2026-09-10');
INSERT INTO achievements(extracurricular_id,title,achievement_date) VALUES (3,'Penghargaan Kemah Bakti Pelajar','2026-08-18'),(9,'Juara 2 Basket Antar Sekolah (Demo)','2026-08-20');
INSERT INTO score_rules(name,points,is_demo) VALUES ('Kehadiran kegiatan',5,1),('Partisipasi kegiatan',10,1),('Prestasi',25,1);
INSERT INTO scores(user_id,extracurricular_id,rule_id,points,note) VALUES (1,3,1,5,'Kehadiran demo'),(1,1,2,10,'Speaking circle');
